### ISSUE TITLE
Doesnt' work

### ISSUE THREAD

**Issue by sitehatchery** [Contargo/redmine-timesheet-plugin#11]
Doesn't work with:

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2

**Comment by sandra-thieme** [comment]
As the [documentation](https://github.com/Contargo/redmine-timesheet-plugin#redmine-compatible) says this plugin currently only works with Redmine 3.3.X.
