### ISSUE TITLE
Error on Redmine 3.2.2

### ISSUE THREAD

**Issue by renzoyugi** [Contargo/redmine-timesheet-plugin#2]
I installed plugin but it doesn´t work 

Error:
"Page not found

The page you were trying to access doesn't exist or has been removed."

Edit: 

Log shows next error: 
"ActionController::RoutingError (uninitialized constant TimesheetsController): ... "

Thanks

**Comment by punycode** [comment]
Thank you for your issue report.

We actually missed a detail in the `README.md` installation instructions:

You actually have to name the plugin folder `timesheet` or else Redmine won't recognize the plugin correctly. We will fix the documentation, meanwhile you should simply rename `plugins/redmine-timesheet-plugin` to `plugins/timesheet` and everything should work as expected.

**Comment by punycode** [comment]
Closed this with 507a22235. More details can be found in #3.
