### ISSUE TITLE
Change name of folder

### ISSUE THREAD

**Issue by ludovicandrieux** [Contargo/redmine-timesheet-plugin#3]
Hi,

When we clone git, we get a folder name redmine-timesheet-plugin and we put it in folder plugins.
But in reality, folder have to be "timesheet".
There is no doc and it's not really a good way to do installation so can you change your name internaly to become redmine-timesheet-plugin ?

Thanks
Ludovic

**Comment by BuJo** [comment]
Hi,

Thank you for your issue report.

We actually missed this detail in the README.md installation instructions, as already reported in Issue #2 .  We will adapt the Documentation to explicitly mention the correct cloning instructions as soon as possible.

**Comment by ludovicandrieux** [comment]
Hi,

Thanks for your response.
 I use lots of redmine plugins and the "standard" is to clone a git repository with the same name. I don't think lots of people take time to read documentation :(
Imho, it should better to change the name of your repo GIT or to change the folder name to use redmine-timesheet-plugin, not to update the documentation.
But it's just my humble opinion.

Ludovic

**Comment by punycode** [comment]
I adapted the documentation to reflect the fact, that a plugin must be installed in a folder named the same as the plugin identifier (507a22235).

While you are right, that it would be nice to just install by doing `git clone $github_url`, I would rather not change the plugin identifier for the following reasons:

* The plugin is actually registered on [redmine.org](http://www.redmine.org/plugins/timesheet) with the current identifier.
* Changing the identifier now will break already working installations cloned from this repository, when they update via `git pull`.

There are several examples of Redmine plugins, that have Git repositories named differently than the actual plugin name, the [plugin which inspired this one](https://github.com/edavis10/redmine-timesheet-plugin) being one example.

Nevertheless, thank you for bringing that forgotten part of the documentation to our attention again… and a happy new year!
