### ISSUE TITLE
Message "translation missing: fr.timesheet_title" in the menu

### ISSUE THREAD

**Issue by la-urre** [Contargo/redmine-timesheet-plugin#4]
This message is displayed in the menu. The translation seems to be present in the config/fr.yml file.

**Comment by BuJo** [comment]
Thank you for the report!  We'll have a look at this and report back.

**Comment by la-urre** [comment]
Renaming the plugin folder to "timesheet" fixed the problem. Thanks for your help and reactivity!

**Comment by BuJo** [comment]
Thank you for reporting back! I hope the rest of your plugin experience is more streamlined and of value to you.
