### ISSUE TITLE
Page not found when clicking on the "Timesheet" menu at the top

### ISSUE THREAD

**Issue by la-urre** [Contargo/redmine-timesheet-plugin#5]
When I click on the "Timesheet" menu at the top, I get redirected to a "Page not found" page. 

I am testing on a local install, the address is the following: http://localhost:8080/timesheet

**Comment by BuJo** [comment]
Hi, thank you for using the plugin.

Have a look at how the folder of the plugin is named in the plugins folder. As per installation instructions it has to be named 'timesheet'. 
The name is important, because of the way the Redmine plugin system works.

Does that solve your problem?

**Comment by la-urre** [comment]
Yes, this fixed the problem! The folder had the name of the archive I got from the redmine website. Thanks for your quick response.

**Comment by BuJo** [comment]
Awesome, thank you!

**Comment by la-urre** [comment]
You could have answered RTF README ! :)

**Comment by BuJo** [comment]
We discussed this issue internally and externally in #3, the issue is "known" but there is no ideal solution...
