### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):

### ISSUE THREAD

**Issue by cchavez** [Contargo/redmine-timesheet-plugin#7]
I'm using redmine 3.3.2.stable.16377 and throws this error:

  Rendered plugins/timesheet/app/views/timesheets/_form.html.erb (11.9ms)
  Rendered plugins/timesheet/app/views/timesheets/_list.html.erb (124.4ms)
  Rendered plugins/timesheet/app/views/timesheets/show.html.erb within layouts/base (144.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (0.6ms)
Completed 200 OK in 485ms (Views: 155.9ms | ActiveRecord: 212.3ms)

ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:529:in `[]='
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:351:in `commit_session'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:226:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/rvm/gems/ruby-2.1.9/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/local/rvm/gems/ruby-2.1.9/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/local/rvm/gems/ruby-2.1.9/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/local/rvm/gems/ruby-2.1.9/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/local/rvm/gems/ruby-2.1.9/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Any help?

**Comment by punycode** [comment]
The problem is the way your Rails installation is configured to manage sessions. This timesheet plugin stores it current settings in the Rails session. This uses a small amount of space. Your other plugins and Redmine itself may store their own information in the session too.

From this part of your stacktrace

```
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:529:in []=' vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:110:inset_cookie'
```

I see that you are using the default cookie based session store. Since cookies can only grow to a maximum size of about 4 kilobyte, you are hitting that size limit.

So you should configure your session store to something persisted on the server side and you should be fine. Regardless of the `timesheet` plugin, this problem might have hit you with any other plugin storing information in the session.

Hope that helps.
